name: build binaries

on:
  push:
    branches:
      - "ci-job-for-cli"
    tags:
      - "[0-9]+.[0-9]+.[0-9]*"

env:
  test_branch_name: "ci-job-for-cli" # Branch which should be named above, used for release process testing

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: generate release info
        id: release-info
        # For release testing we don't have a version to use from a tag
        # so we generate a stand in that's a time stamp
        run: |
          if [[ ${{ endsWith( env.test_branch_name, github.ref ) }} ]]; then
            tag=$(date +'%Y%m%d%H%M')
          else
            # This is a bit of a hack, but we need to get the tag name from the ref
            tag=$(echo "${{ github.ref }}" | cut -d'/' -f3)
          fi
          echo "release-tag=${tag}" >> $GITHUB_OUTPUT
        shell: bash

      - name: create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          draft: ${{ endsWith( env.test_branch_name, github.ref ) }}
          tag_name: ${{ steps.release-info.outputs.release-tag }}

  build:
    strategy:
      matrix:
        # windows-11-arm currently fails build due to https://github.com/briansmith/ring/issues/1167
        # macos-latest is ARM, ubuntu-latest is x86, windows-latest is x86
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: create_release
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: get executable binary_suffix
        id: platform-info
        run: |
          if [[ ${{ runner.os }} == "Windows" ]]; then
            binary_suffix=".exe"
          else
            binary_suffix=""
          fi
          echo "binary_suffix=${binary_suffix}" >> $GITHUB_OUTPUT
        shell: bash

      - name: install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1 # We need 1.12.0 or later for Windows ARM64 support
        with:
          # Provisionally pinning version pre 1.81 sorting changes
          toolchain: 1.80.1
          override: true

      - name: install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
          version: 1.0
        if: runner.os == 'Linux' # This action only works on Ubuntu

      - name: set RUSTFLAGS # Note this is necessary because the setting in .cargo/config.toml doesn't propagate to dependency builds
        run: echo "RUSTFLAGS=--cfg tokio_unstable" >> $GITHUB_ENV
        shell: bash

      - name: build libra binary
        run: |
          cargo b --release -p libra

      - name: check binary runs-on
        run: target/release/libra${{ steps.platform-info.binary_suffix }} version
        shell: bash

      - name: rename to plafrorm specific name
        id: artifact-info
        run: |
          echo "artifact_name=target/release/libra-${{ runner.os }}-${{ runner.arch }}${{ steps.platform-info.binary_suffix }}" >> $GITHUB_OUTPUT
          mv target/release/libra${binary_suffix} ${artifact_name}
        shell: bash

      - name: print binary artifact name
        run: |
          echo "artifact_name: ${{ steps.artifact-info.artifact_name }}"
        shell: bash

      - name: upload binary to release # upload the binary as a release artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-info.outputs.release-tag }}
          files: ${{ steps.artifact-info.artifact_name }}
          overwrite: true
